apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: k8s-csrapprove
  name: csr-approver
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-csrapprove
  labels:
    app: k8s-csrapprove
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csr-approver
subjects:
- kind: ServiceAccount
  name: k8s-csrapprove
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-csrapprove
  labels:
    app: k8s-csrapprove
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-csrapprove
  labels:
    app: k8s-csrapprove
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-csrapprove
  template:
    metadata:
      labels:
        app: k8s-csrapprove
    spec:
      containers:
      - name: k8s-csrapprove
        image: docker.dolansoft.org/dolansoft/k8s-csrapprove:957d36712885ef8ef0b97605e4c29d3359664897
        args:
          - --logtostderr
        resources:
          requests:
            memory: 32Mi
            cpu: 10m
          limits:
            memory: 64Mi